services:
  app:
    build: .
    container_name: hubspot-integration
    ports:
      - "${SPRING_SERVER_PORT}:${SPRING_SERVER_PORT}"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - hubspot-network
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: hubspot-postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hubspot-network
    restart: unless-stopped

networks:
  hubspot-network:
    driver: bridge

volumes:
  postgres_data:
