services:
  app:
    build: .
    container_name: hubspot-integration
    ports:
      - "${SPRING_SERVER_PORT}:${SPRING_SERVER_PORT}"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - hubspot-network
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: hubspot-postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hubspot-network
    restart: unless-stopped

  redis:
    image: redis:7.2
    container_name: hubspot-redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: unless-stopped
    networks:
      - hubspot-network
    env_file:
      - .env

networks:
  hubspot-network:
    driver: bridge

volumes:
  postgres_data:
