server:
  port: ${SPRING_SERVER_PORT:3001}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 5s

  security:
    oauth2:
      client:
        registration:
          hubspot:
            client-id: ${HUBSPOT_CLIENT_ID}
            client-secret: ${HUBSPOT_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${HUBSPOT_REDIRECT_URI}
            client-name: "HubSpot"
            scope: ${HUBSPOT_SCOPES}
        provider:
          hubspot:
            authorization-uri: ${HUBSPOT_OAUTH_URL}
            token-uri: ${HUBSPOT_OAUTH_TOKEN_URL}

hubspot:
  api:
    contacts-url: ${HUBSPOT_CRM_CONTACTS_URL}

# Rate Limiter Configuration
# This configuration is used to limit the number of requests to the HubSpot API
# to prevent exceeding the rate limits set by HubSpot.
rate-limiter:
  max-requests: 110
  window-seconds: 10
